// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: donation.sql

package db

import (
	"context"
)

const createDonation = `-- name: CreateDonation :one
insert into donation(user, channel, send_from, amount, text)    
VALUES(?, ?, ?, ?, ?)
RETURNING id, user, channel, send_from, amount, text, timestamp
`

type CreateDonationParams struct {
	User     string
	Channel  string
	SendFrom string
	Amount   int64
	Text     string
}

func (q *Queries) CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error) {
	row := q.db.QueryRowContext(ctx, createDonation,
		arg.User,
		arg.Channel,
		arg.SendFrom,
		arg.Amount,
		arg.Text,
	)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.Channel,
		&i.SendFrom,
		&i.Amount,
		&i.Text,
		&i.Timestamp,
	)
	return i, err
}
