// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: donation.sql

package db

import (
	"context"
	"time"
)

const createDonation = `-- name: CreateDonation :one
insert into donation(user, channel, send_from, amount, text)    
VALUES(?, ?, ?, ?, ?)
RETURNING id, user, channel, send_from, amount, text, timestamp
`

type CreateDonationParams struct {
	User     string
	Channel  string
	SendFrom string
	Amount   int64
	Text     string
}

func (q *Queries) CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error) {
	row := q.db.QueryRowContext(ctx, createDonation,
		arg.User,
		arg.Channel,
		arg.SendFrom,
		arg.Amount,
		arg.Text,
	)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.Channel,
		&i.SendFrom,
		&i.Amount,
		&i.Text,
		&i.Timestamp,
	)
	return i, err
}

const getAllStreamers = `-- name: GetAllStreamers :many
SELECT DISTINCT d.channel
FROM donation d
`

func (q *Queries) GetAllStreamers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllStreamers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var channel string
		if err := rows.Scan(&channel); err != nil {
			return nil, err
		}
		items = append(items, channel)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSumDonationByStreamer = `-- name: GetSumDonationByStreamer :many
SELECT
    CAST(COALESCE(SUM(d.amount), 0) AS INTEGER) AS amount,
    CAST(strftime('%Y-%m-%d', MIN(d."timestamp")) AS TEXT)  AS StartingDate,
    CAST(strftime('%Y-%m-%d', MAX(d."timestamp")) AS TEXT)  AS EndingDate,
    d.channel
FROM donation d 
WHERE d."timestamp" BETWEEN ? AND ?
GROUP BY d.channel
`

type GetSumDonationByStreamerParams struct {
	FromTimestamp time.Time
	ToTimestamp   time.Time
}

type GetSumDonationByStreamerRow struct {
	Amount       int64
	Startingdate string
	Endingdate   string
	Channel      string
}

func (q *Queries) GetSumDonationByStreamer(ctx context.Context, arg GetSumDonationByStreamerParams) ([]GetSumDonationByStreamerRow, error) {
	rows, err := q.db.QueryContext(ctx, getSumDonationByStreamer, arg.FromTimestamp, arg.ToTimestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSumDonationByStreamerRow
	for rows.Next() {
		var i GetSumDonationByStreamerRow
		if err := rows.Scan(
			&i.Amount,
			&i.Startingdate,
			&i.Endingdate,
			&i.Channel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastDonations = `-- name: getLastDonations :many
SELECT d.id, d.user, d.channel, d.send_from, d.amount, d.text, d.timestamp
FROM donation d
ORDER BY d.timestamp DESC
LIMIT ?2 OFFSET ?1
`

type getLastDonationsParams struct {
	Offset int64
	Limit  int64
}

func (q *Queries) getLastDonations(ctx context.Context, arg getLastDonationsParams) ([]Donation, error) {
	rows, err := q.db.QueryContext(ctx, getLastDonations, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Donation
	for rows.Next() {
		var i Donation
		if err := rows.Scan(
			&i.ID,
			&i.User,
			&i.Channel,
			&i.SendFrom,
			&i.Amount,
			&i.Text,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastDonationsByStreamer = `-- name: getLastDonationsByStreamer :many
SELECT d.id, d.user, d.channel, d.send_from, d.amount, d.text, d.timestamp
FROM donation d
WHERE d.channel = ?1
ORDER BY d.timestamp DESC
LIMIT ?3 OFFSET ?2
`

type getLastDonationsByStreamerParams struct {
	Channel string
	Offset  int64
	Limit   int64
}

func (q *Queries) getLastDonationsByStreamer(ctx context.Context, arg getLastDonationsByStreamerParams) ([]Donation, error) {
	rows, err := q.db.QueryContext(ctx, getLastDonationsByStreamer, arg.Channel, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Donation
	for rows.Next() {
		var i Donation
		if err := rows.Scan(
			&i.ID,
			&i.User,
			&i.Channel,
			&i.SendFrom,
			&i.Amount,
			&i.Text,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
