// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Donation struct {
	ID        int64
	User      string
	Channel   string
	SendFrom  string
	Amount    int64
	Text      string
	Timestamp time.Time
}
